name: Update Backend

on: [push]

jobs:
    Error-Check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Python Environment Setup
              uses: actions/setup-python@v2
            - name: Install dependencies
              run: |
                  python -m pip install -r requirements.txt
            - name: Lint filese
              run: |
                  # Lint all Python files
                  pylint --disable=C,R . --recursive=true

    Restart-Server:
        runs-on: ubuntu-latest
        needs: [Error-Check]
        steps:
            - name: Call API
              run: |
                  # Call your API here, using the API key stored in the API_KEY environment variable
                  curl -X POST https://api.example.com/endpoint -H "Authorization: Bearer ${{ secrets.API_KEY }}"
